site_name: Open AI Models Java Sdk
site_url: https://openai-java-sdk.devlive.org
site_author: qinamoQ
site_description: >-
  Provides an easy-to-use SDK for Java developers to interact with the APIs of open AI models.

repo_name: devlive-community/openai-java-sdk
repo_url: https://github.com/devlive-community/openai-java-sdk
edit_uri: "https://github.com/devlive-community/openai-java-sdk/blob/master/docs/docs"

banners:
  - title: OpenAi Java SDK &nbsp; <em>2023.12.1</em> &nbsp; is released
    link: /release-latest.html
    description: <a href="https://github.com/devlive-community/openai-java-sdk" class="text-white"> Do you ❤️ DataCap? Give us a 🌟 on GitHub </a>

copyright: Copyright &copy; 2023 devlive-community

use_directory_urls: false

theme:
  name: material
  custom_dir: overrides

  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - navigation.expand
    - navigation.prune
    - abbr
    - attr_list
    - pymdownx.snippets
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Chinese (Simplified)
      link: /zh/
      lang: zh

extra_css:
  - assets/stylesheets/main.2f34a6de.min.css
  - assets/stylesheets/palette.ecc776e4.min.css
extra_javascript:
  - assets/javascript/main.2dasf4fv.js

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - abbr

plugins:
  - i18n:
      reconfigure_material: true
      default_language: en
      languages:
        - locale: zh
          name: Chinese (Simplified)
          build: true
          default: false
          nav_translations:
            NavReleaseNote: 更新日志
        - locale: en
          name: English
          build: true
          default: true
          nav_translations:
            NavReleaseNote: Release Note
  - redirects:
      redirect_maps:
        release-latest.md: release/latest.md

nav:
  - index.md
  - Reference:
      - Stream (Not provider):
          - reference/stream/console.md
      - Open Ai:
        - reference/openai/users.md
        - reference/openai/models.md
        - reference/openai/completions.md
        - reference/openai/completions_chat.md
        - reference/openai/images.md
        - reference/openai/embeddings.md
        - reference/openai/audio.md
        - reference/openai/moderations.md
        - reference/openai/edits.md
        - reference/openai/files.md
        - reference/openai/fine_tunes.md
        - reference/openai/assistants.md
      - Azure Open Ai:
          - reference/azure/completions.md
          - reference/azure/completions_chat.md
      - Anthropic Claude:
          - reference/anthropic/completions.md
      - Google PaLM:
          - reference/google_palm/completions.md
          - reference/google_palm/chat.md
  - NavReleaseNote:
      - release/latest.md
      - released.md
  - powered_by.md
